// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: identity_events.proto

package identity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityRegistered struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID           string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Email        string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Passwordhash string `protobuf:"bytes,3,opt,name=passwordhash,proto3" json:"passwordhash,omitempty"`
}

func (x *IdentityRegistered) Reset() {
	*x = IdentityRegistered{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentityRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityRegistered) ProtoMessage() {}

func (x *IdentityRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_identity_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityRegistered.ProtoReflect.Descriptor instead.
func (*IdentityRegistered) Descriptor() ([]byte, []int) {
	return file_identity_events_proto_rawDescGZIP(), []int{0}
}

func (x *IdentityRegistered) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *IdentityRegistered) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *IdentityRegistered) GetPasswordhash() string {
	if x != nil {
		return x.Passwordhash
	}
	return ""
}

type IdentityLoggedIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID string `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
}

func (x *IdentityLoggedIn) Reset() {
	*x = IdentityLoggedIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentityLoggedIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityLoggedIn) ProtoMessage() {}

func (x *IdentityLoggedIn) ProtoReflect() protoreflect.Message {
	mi := &file_identity_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityLoggedIn.ProtoReflect.Descriptor instead.
func (*IdentityLoggedIn) Descriptor() ([]byte, []int) {
	return file_identity_events_proto_rawDescGZIP(), []int{1}
}

func (x *IdentityLoggedIn) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

type IdentityLoggedOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID string `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
}

func (x *IdentityLoggedOut) Reset() {
	*x = IdentityLoggedOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentityLoggedOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityLoggedOut) ProtoMessage() {}

func (x *IdentityLoggedOut) ProtoReflect() protoreflect.Message {
	mi := &file_identity_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityLoggedOut.ProtoReflect.Descriptor instead.
func (*IdentityLoggedOut) Descriptor() ([]byte, []int) {
	return file_identity_events_proto_rawDescGZIP(), []int{2}
}

func (x *IdentityLoggedOut) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

var File_identity_events_proto protoreflect.FileDescriptor

var file_identity_events_proto_rawDesc = []byte{
	0x0a, 0x15, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x22, 0x5e, 0x0a, 0x12, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x22, 0x0a,
	0x0c, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x68, 0x61, 0x73,
	0x68, 0x22, 0x30, 0x0a, 0x10, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c, 0x6f, 0x67,
	0x67, 0x65, 0x64, 0x49, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x22, 0x31, 0x0a, 0x11, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c,
	0x6f, 0x67, 0x67, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x42, 0x1d, 0x5a, 0x1b, 0x2e, 0x2e, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_identity_events_proto_rawDescOnce sync.Once
	file_identity_events_proto_rawDescData = file_identity_events_proto_rawDesc
)

func file_identity_events_proto_rawDescGZIP() []byte {
	file_identity_events_proto_rawDescOnce.Do(func() {
		file_identity_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_identity_events_proto_rawDescData)
	})
	return file_identity_events_proto_rawDescData
}

var file_identity_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_identity_events_proto_goTypes = []interface{}{
	(*IdentityRegistered)(nil), // 0: identity.IdentityRegistered
	(*IdentityLoggedIn)(nil),   // 1: identity.IdentityLoggedIn
	(*IdentityLoggedOut)(nil),  // 2: identity.IdentityLoggedOut
}
var file_identity_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_identity_events_proto_init() }
func file_identity_events_proto_init() {
	if File_identity_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_identity_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentityRegistered); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentityLoggedIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_events_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentityLoggedOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_identity_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_identity_events_proto_goTypes,
		DependencyIndexes: file_identity_events_proto_depIdxs,
		MessageInfos:      file_identity_events_proto_msgTypes,
	}.Build()
	File_identity_events_proto = out.File
	file_identity_events_proto_rawDesc = nil
	file_identity_events_proto_goTypes = nil
	file_identity_events_proto_depIdxs = nil
}
