version: "3.9"

volumes:
    postgressql_data:

networks:
    service_net:

services:
    postgressql:
        image: postgres
        container_name: postgres
        restart: always
        volumes:
            - postgressql_data:/var/lib/postgresql/data:rw
        ports:
            - "5432"
        networks:
            - service_net
        env_file:
            - ./environments/postgres.env

    example-service:
        image: example-service:latest
        container_name: service
        depends_on:
            - postgressql
        ports:
            - "8080:8080"
        networks:
            - service_net
        env_file:
            - ./environments/example-service.env
