version: "3.9"

volumes:
  postgressql_data:
  mongo_data:

networks:
  service_net:
    driver: bridge

services:
  ia_zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: ia_zookeeper
    env_file:
      - ./environments/zookeeper.env
    ports:
      - 2181:2181
    networks:
      - service_net

  ia_kafka:
    image: wurstmeister/kafka:latest
    container_name: ia_kafka
    depends_on:
      - ia_zookeeper
    env_file:
      - ./environments/kafka.env
    ports:
      - 9092:9092
    networks:
      - service_net

  ia_mongo:
    image: mongo:latest
    container_name: ia_mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=eventstore
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo_data:/data/db
      - ./inits/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    networks:
      - service_net

  ia:
    image: example-service:latest
    container_name: ia_service
    restart: always
    depends_on:
      - ia_mongo
      - ia_kafka
    ports:
      - "5000:5000"
    networks:
      - service_net
    env_file:
      - ./environments/example-service.env
