version: "3.9"

volumes:
  example-service-postgressql_data:

networks:
  service_net:

services:
  example-service-postgressql:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - example-service-postgressql_data:/var/lib/postgresql/data:rw
    ports:
      - "5432"
    networks:
      - service_net
    env_file:
      - ./environments/postgres.env
    
  pulsar:
    image: apachepulsar/pulsar
    restart: unless-stopped
    expose:
      - 8080
      - 6650
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone --advertised-address localhost"

  dashboard:
    image: apachepulsar/pulsar-dashboard
    depends_on:
      - pulsar
    ports:
      - "5001:80"
    environment:
      - SERVICE_URL=http://localhost:8080

  example-service:
    image: example-service:latest
    container_name: service
    restart: always
    depends_on:
      - example-service-postgressql
      - pulsar
    ports:
      - "5000:5000"
    networks:
      - service_net
    env_file:
      - ./environments/example-service.env
