#!/bin/sh
curl -X POST -u some1@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some2@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some3@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some4@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some5@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some6@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some7@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some8@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some9@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some10@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some11@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some12@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some13@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some14@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some15@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some16@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some17@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some18@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some19@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some20@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some21@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some22@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some23@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some24@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some25@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some26@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some27@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some28@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some29@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some30@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some31@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some32@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some33@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some34@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some35@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some36@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some37@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some38@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some39@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some40@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some41@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some42@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some43@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some44@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some45@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some46@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some47@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some48@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some49@email:P@ssw0rd http://localhost:80/api/v1/identities
curl -X POST -u some50@email:P@ssw0rd http://localhost:80/api/v1/identities