# https://github.com/qdm12/godevcontainer
FROM qmcgaw/godevcontainer:alpine

# Tools
#   go-outline: https://github.com/ramya-rao-a/go-outline
#   gomodifytags: https://github.com/fatih/gomodifytags
#   goplay: https://github.com/haya14busa/goplay
#   gotests: https://github.com/cweill/gotests
#   delve: https://github.com/go-delve/delve
#   mockery: https://github.com/vektra/mockery
#   gomock/mockgen: https://github.com/golang/mock
#   gopls: https://pkg.go.dev/golang.org/x/tools/gopls
#   golangci-lint: https://github.com/golangci/golangci-lint
#   impl: https://github.com/josharian/impl
#   gopkgs: https://github.com/uudashr/gopkgs
#   kubectl: https://kubernetes.io/docs/tasks/tools/
#   stern: https://github.com/wercker/stern
#   kubectx: https://github.com/ahmetb/kubectx
#   kubens: https://github.com/ahmetb/kubectx
#   helm: https://helm.sh/
