version: "3.8"

volumes:
  ia_mongo_data:

networks:
  service_net:
    driver: overlay
  tracing:
    external: true
    name: tracing_jaeger

services:
  ia_api:
    image: ghcr.io/hywmongous/golang-template:latest
    restart: always
    depends_on:
      - ia_mongo
    networks:
      - service_net
      - tracing
    env_file:
      - ./api/environment.env

  ia_mongo:
    image: mongo:latest
    restart: always
    env_file:
      - ./mongodb/environment.env
    volumes:
      - ia_mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      - service_net
    logging:
      driver: "none"
