version: "3.8"

volumes:
  ia_mongo_data:

networks:
  service_net:
    driver: overlay
    ipam:
      config:
        - subnet: 10.11.0.0/16

services:
  ia_api:
    image: ghcr.io/hywmongous/golang-template:main
    restart: always
    depends_on:
      - ia_mongo
      - ia_kafka
    networks:
      - service_net
    env_file:
      - ./api/environment.env
    ports:
      - 80:5000

  ia_zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: always
    env_file:
      - ./zookeeper/environment.env
    networks:
      - service_net
    logging:
      driver: "none"

  ia_kafka:
    image: wurstmeister/kafka:latest
    restart: always
    depends_on:
      - ia_zookeeper
    env_file:
      - ./kafka/environment.env
    networks:
      - service_net
    logging:
      driver: "none"

  ia_mongo:
    image: mongo:latest
    restart: always
    env_file:
      - ./mongodb/environment.env
    volumes:
      - ia_mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      - service_net
    logging:
      driver: "none"
