// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: usecases.proto

package application

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterIdentityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *RegisterIdentityRequest) Reset() {
	*x = RegisterIdentityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usecases_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterIdentityRequest) ProtoMessage() {}

func (x *RegisterIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterIdentityRequest.ProtoReflect.Descriptor instead.
func (*RegisterIdentityRequest) Descriptor() ([]byte, []int) {
	return file_usecases_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterIdentityRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterIdentityRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterIdentityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RegisterIdentityResponse) Reset() {
	*x = RegisterIdentityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usecases_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterIdentityResponse) ProtoMessage() {}

func (x *RegisterIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterIdentityResponse.ProtoReflect.Descriptor instead.
func (*RegisterIdentityResponse) Descriptor() ([]byte, []int) {
	return file_usecases_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterIdentityResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LoginIdentityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *LoginIdentityRequest) Reset() {
	*x = LoginIdentityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usecases_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginIdentityRequest) ProtoMessage() {}

func (x *LoginIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginIdentityRequest.ProtoReflect.Descriptor instead.
func (*LoginIdentityRequest) Descriptor() ([]byte, []int) {
	return file_usecases_proto_rawDescGZIP(), []int{2}
}

func (x *LoginIdentityRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginIdentityRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginIdentityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID string `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
}

func (x *LoginIdentityResponse) Reset() {
	*x = LoginIdentityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usecases_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginIdentityResponse) ProtoMessage() {}

func (x *LoginIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginIdentityResponse.ProtoReflect.Descriptor instead.
func (*LoginIdentityResponse) Descriptor() ([]byte, []int) {
	return file_usecases_proto_rawDescGZIP(), []int{3}
}

func (x *LoginIdentityResponse) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

type LogoutIdentityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email     string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	SessionID string `protobuf:"bytes,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
}

func (x *LogoutIdentityRequest) Reset() {
	*x = LogoutIdentityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usecases_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutIdentityRequest) ProtoMessage() {}

func (x *LogoutIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutIdentityRequest.ProtoReflect.Descriptor instead.
func (*LogoutIdentityRequest) Descriptor() ([]byte, []int) {
	return file_usecases_proto_rawDescGZIP(), []int{4}
}

func (x *LogoutIdentityRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LogoutIdentityRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

type LogoutIdentityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Revoked bool `protobuf:"varint,1,opt,name=revoked,proto3" json:"revoked,omitempty"`
}

func (x *LogoutIdentityResponse) Reset() {
	*x = LogoutIdentityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usecases_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutIdentityResponse) ProtoMessage() {}

func (x *LogoutIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutIdentityResponse.ProtoReflect.Descriptor instead.
func (*LogoutIdentityResponse) Descriptor() ([]byte, []int) {
	return file_usecases_proto_rawDescGZIP(), []int{5}
}

func (x *LogoutIdentityResponse) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

var File_usecases_proto protoreflect.FileDescriptor

var file_usecases_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x75, 0x73, 0x65, 0x63, 0x61, 0x73, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4b, 0x0a,
	0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x2a, 0x0a, 0x18, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x48, 0x0a, 0x14, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x22, 0x35, 0x0a, 0x15, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0x4b, 0x0a, 0x15, 0x4c, 0x6f, 0x67, 0x6f, 0x75,
	0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x22, 0x32, 0x0a, 0x16, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x72, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x72, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x64, 0x42, 0x19, 0x5a, 0x17, 0x2e, 0x2e, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_usecases_proto_rawDescOnce sync.Once
	file_usecases_proto_rawDescData = file_usecases_proto_rawDesc
)

func file_usecases_proto_rawDescGZIP() []byte {
	file_usecases_proto_rawDescOnce.Do(func() {
		file_usecases_proto_rawDescData = protoimpl.X.CompressGZIP(file_usecases_proto_rawDescData)
	})
	return file_usecases_proto_rawDescData
}

var file_usecases_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_usecases_proto_goTypes = []interface{}{
	(*RegisterIdentityRequest)(nil),  // 0: application.RegisterIdentityRequest
	(*RegisterIdentityResponse)(nil), // 1: application.RegisterIdentityResponse
	(*LoginIdentityRequest)(nil),     // 2: application.LoginIdentityRequest
	(*LoginIdentityResponse)(nil),    // 3: application.LoginIdentityResponse
	(*LogoutIdentityRequest)(nil),    // 4: application.LogoutIdentityRequest
	(*LogoutIdentityResponse)(nil),   // 5: application.LogoutIdentityResponse
}
var file_usecases_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_usecases_proto_init() }
func file_usecases_proto_init() {
	if File_usecases_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_usecases_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterIdentityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usecases_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterIdentityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usecases_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginIdentityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usecases_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginIdentityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usecases_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogoutIdentityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usecases_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogoutIdentityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_usecases_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_usecases_proto_goTypes,
		DependencyIndexes: file_usecases_proto_depIdxs,
		MessageInfos:      file_usecases_proto_msgTypes,
	}.Build()
	File_usecases_proto = out.File
	file_usecases_proto_rawDesc = nil
	file_usecases_proto_goTypes = nil
	file_usecases_proto_depIdxs = nil
}
