name: ghcr docker image publishing

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ghcr-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
        run: make docker_build
