name: ghcr docker image publishing

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ghcr-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        name: Login to GitHub Container Registry
        with:
          registry: ghcr.io
          # The login of the user that initiated the workflow run.
          username: ${{ github.actor }}
          # A token to authenticate on behalf of the GitHub App installed on your repository.
          password: ${{ github.token }}
      - uses: docker/build-push-action@v2
        # Allows us to retrieve the output from the build
        id: docker_image_builder
        with:
          # Because the Dockerfile is within /build/docker
          context: ./../../
          file: ./build/docker/Dockerfile
          push: true
          tags: ${{ github.repository }}:latest
      - name: Docker image digest
        run: echo ${{ steps.docker_image_builder.outputs.digest }}
