name: Go formatting

on:
  push:
    paths:
      - "**.go"
  pull_request:
    paths:
      - "**.go"
  workflow_dispatch:

jobs:
  go-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gofmt
        run: gofmt -s -w .
