name: Go unit tests

on:
  push:
    paths:
      - "**.go"
  pull_request:
    paths:
      - "**.go"
  workflow_dispatch:

jobs:
  go-test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - name: Test
        run: go test ./...
      - uses: codecov/codecov-action@v2
        name: Upload coverage to Codecov
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.platform }},go-${{ matrix.go-version }}
          fail_ci_if_error: true
          verbose: true
