name: Snyk Dock

on: push

env:
  # https://docs.snyk.io/features/snyk-cli/guides-for-our-cli/set-severity-thresholds-for-cli-tests
  SNYK_THRESHOLD: low #low|medium|high|critical
  SNYK_OUT_FILE: snyk.sarif

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Snyk Docker
        # https://github.com/snyk/actions/tree/master/docker
        uses: snyk/actions/docker@master
        # Snyk can be used to break the build when it detects vulnerabilities.
        # In this case we want to upload the issues to GitHub Code Scanning
        continue-on-error: true
        env:
          # In order to use the Snyk Action you will need to have a Snyk API token.
          # More details in https://github.com/snyk/actions#getting-your-snyk-token
          # or you can signup for free at https://snyk.io/login
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.REGISTRY }}/${{ github.repository }}
          args:
            --file=./build/docker/Dockerfile
            --severity-threshold=${{ env.SNYK_THRESHOLD }}

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ env.SNYK_OUT_FILE }}
